// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// nufft_1d1
Rcpp::ComplexVector nufft_1d1(std::vector<double> xj, std::vector<std::complex<double>> cj, int n1, double tol);
RcppExport SEXP _finufft_nufft_1d1(SEXP xjSEXP, SEXP cjSEXP, SEXP n1SEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type xj(xjSEXP);
    Rcpp::traits::input_parameter< std::vector<std::complex<double>> >::type cj(cjSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(nufft_1d1(xj, cj, n1, tol));
    return rcpp_result_gen;
END_RCPP
}
// nufft_1d2
Rcpp::ComplexVector nufft_1d2(std::vector<double> xj, std::vector<std::complex<double>> fk, double tol);
RcppExport SEXP _finufft_nufft_1d2(SEXP xjSEXP, SEXP fkSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type xj(xjSEXP);
    Rcpp::traits::input_parameter< std::vector<std::complex<double>> >::type fk(fkSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(nufft_1d2(xj, fk, tol));
    return rcpp_result_gen;
END_RCPP
}
// nufft_1d3
Rcpp::ComplexVector nufft_1d3(std::vector<double> xj, std::vector<std::complex<double>> cj, std::vector<double> sk, double tol);
RcppExport SEXP _finufft_nufft_1d3(SEXP xjSEXP, SEXP cjSEXP, SEXP skSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type xj(xjSEXP);
    Rcpp::traits::input_parameter< std::vector<std::complex<double>> >::type cj(cjSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type sk(skSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(nufft_1d3(xj, cj, sk, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_finufft_nufft_1d1", (DL_FUNC) &_finufft_nufft_1d1, 4},
    {"_finufft_nufft_1d2", (DL_FUNC) &_finufft_nufft_1d2, 3},
    {"_finufft_nufft_1d3", (DL_FUNC) &_finufft_nufft_1d3, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_finufft(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
