# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nfft <- function(x, c, N, tol = 1e-9) {
    .Call(`_finufft_nfft`, x, c, N, tol)
}

